// AniFlux Mock Anime Catalog Data
// Posters sourced from publicly accessible CDNs and placeholder services

export const ANIME_CATALOG = [
  {
    id: 1,
    title: 'Neon Blade Chronicles',
    slug: 'neon-blade-chronicles',
    synopsis: 'In a dystopian future where AI-samurai battle for control of Neo-Tokyo, one rogue fighter holds the key to humanity\'s salvation.',
    genre: ['Action', 'Sci-Fi', 'Cyberpunk'],
    episodes: 24,
    rating: 9.2,
    year: 2024,
    studio: 'CyberAnime Studio',
    status: 'Airing',
    poster: 'https://picsum.photos/seed/anime1/300/450',
    banner: 'https://picsum.photos/seed/banner1/1920/1080',
    videoPreview: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tags: ['1080p', 'Subbed', 'Dubbed'],
    featured: true,
    trending: true,
    topRated: true,
    waifuFav: false,
  },
  {
    id: 2,
    title: 'Sakura Protocol',
    slug: 'sakura-protocol',
    synopsis: 'A genius hacker and a spirit-wielder must unite to stop a digital demon from consuming every network on earth.',
    genre: ['Fantasy', 'Thriller', 'Romance'],
    episodes: 12,
    rating: 8.7,
    year: 2024,
    studio: 'Moonbloom Animation',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime2/300/450',
    banner: 'https://picsum.photos/seed/banner2/1920/1080',
    videoPreview: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: true,
    topRated: true,
    waifuFav: true,
  },
  {
    id: 3,
    title: 'Phantom Rebellion',
    slug: 'phantom-rebellion',
    synopsis: 'Secret society ninjas, sentient mechs, and ancient gods collide in this jaw-dropping action epic.',
    genre: ['Action', 'Mecha', 'Mythology'],
    episodes: 36,
    rating: 9.5,
    year: 2023,
    studio: 'OmegaForge',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime3/300/450',
    banner: 'https://picsum.photos/seed/banner3/1920/1080',
    videoPreview: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    tags: ['4K', 'Subbed', 'Dubbed'],
    featured: true,
    trending: false,
    topRated: true,
    waifuFav: false,
  },
  {
    id: 4,
    title: 'Waifu Academy',
    slug: 'waifu-academy',
    synopsis: 'At an academy where magical girls and cyborg students coexist, friendships are forged and hearts shattered.',
    genre: ['Slice of Life', 'Romance', 'Comedy'],
    episodes: 26,
    rating: 8.4,
    year: 2024,
    studio: 'PinkCloud Works',
    status: 'Airing',
    poster: 'https://picsum.photos/seed/anime4/300/450',
    banner: 'https://picsum.photos/seed/banner4/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: true,
    topRated: false,
    waifuFav: true,
  },
  {
    id: 5,
    title: 'Void Sovereign',
    slug: 'void-sovereign',
    synopsis: 'A young swordsman consumed by darkness must master the void to reclaim his humanity before it\'s too late.',
    genre: ['Dark Fantasy', 'Action', 'Horror'],
    episodes: 13,
    rating: 9.0,
    year: 2023,
    studio: 'DarkForge Animation',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime5/300/450',
    banner: 'https://picsum.photos/seed/banner5/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: false,
    topRated: true,
    waifuFav: false,
  },
  {
    id: 6,
    title: 'Galaxy Idol',
    slug: 'galaxy-idol',
    synopsis: 'Pop stars with cosmic powers compete in an interstellar idol competition to become the voice of the universe.',
    genre: ['Music', 'Sci-Fi', 'Comedy'],
    episodes: 24,
    rating: 8.1,
    year: 2024,
    studio: 'StarDust Entertainment',
    status: 'Airing',
    poster: 'https://picsum.photos/seed/anime6/300/450',
    banner: 'https://picsum.photos/seed/banner6/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: true,
    topRated: false,
    waifuFav: true,
  },
  {
    id: 7,
    title: 'Ryū no Ken',
    slug: 'ryu-no-ken',
    synopsis: 'The last dragon knight must forge seven legendary weapons before the demon emperor awakens from his millennium sleep.',
    genre: ['Action', 'Adventure', 'Fantasy'],
    episodes: 52,
    rating: 9.3,
    year: 2022,
    studio: 'DragonBreath Studio',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime7/300/450',
    banner: 'https://picsum.photos/seed/banner7/1920/1080',
    videoPreview: null,
    tags: ['4K', 'Subbed', 'Dubbed'],
    featured: false,
    trending: false,
    topRated: true,
    waifuFav: false,
  },
  {
    id: 8,
    title: 'Hana & The Oracle',
    slug: 'hana-and-the-oracle',
    synopsis: 'A timid shrine maiden discovers she can speak with gods — and that the fate of two realms rests on her voice.',
    genre: ['Supernatural', 'Romance', 'Drama'],
    episodes: 12,
    rating: 8.9,
    year: 2024,
    studio: 'Serenity Films',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime8/300/450',
    banner: 'https://picsum.photos/seed/banner8/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: false,
    topRated: false,
    waifuFav: true,
  },
  {
    id: 9,
    title: 'Zero Protocol',
    slug: 'zero-protocol',
    synopsis: 'An elite squad of AI operatives hunts a rogue virus that threatens to erase all digital consciousness.',
    genre: ['Sci-Fi', 'Thriller', 'Action'],
    episodes: 24,
    rating: 8.6,
    year: 2023,
    studio: 'ByteForge',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime9/300/450',
    banner: 'https://picsum.photos/seed/banner9/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed', 'Dubbed'],
    featured: false,
    trending: false,
    topRated: true,
    waifuFav: false,
  },
  {
    id: 10,
    title: 'Starbound Odyssey',
    slug: 'starbound-odyssey',
    synopsis: 'Five strangers stranded on an alien world must overcome their differences to build a ship and find their way home.',
    genre: ['Adventure', 'Sci-Fi', 'Drama'],
    episodes: 26,
    rating: 8.8,
    year: 2024,
    studio: 'NebulaCraft',
    status: 'Airing',
    poster: 'https://picsum.photos/seed/anime10/300/450',
    banner: 'https://picsum.photos/seed/banner10/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: true,
    topRated: false,
    waifuFav: false,
  },
  {
    id: 11,
    title: 'Crimson Throne',
    slug: 'crimson-throne',
    synopsis: 'Political intrigue, betrayal, and supernatural powers collide in a bloody war for the empire\'s throne.',
    genre: ['Political', 'Fantasy', 'Drama'],
    episodes: 24,
    rating: 9.1,
    year: 2023,
    studio: 'IronQuill Animation',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime11/300/450',
    banner: 'https://picsum.photos/seed/banner11/1920/1080',
    videoPreview: null,
    tags: ['4K', 'Subbed'],
    featured: false,
    trending: false,
    topRated: true,
    waifuFav: false,
  },
  {
    id: 12,
    title: 'Mochi Dreams',
    slug: 'mochi-dreams',
    synopsis: 'A cozy slice-of-life following a bakery witch who crafts enchanted sweets that grant mysterious wishes.',
    genre: ['Slice of Life', 'Fantasy', 'Comedy'],
    episodes: 13,
    rating: 8.2,
    year: 2024,
    studio: 'SweetRoll Studios',
    status: 'Completed',
    poster: 'https://picsum.photos/seed/anime12/300/450',
    banner: 'https://picsum.photos/seed/banner12/1920/1080',
    videoPreview: null,
    tags: ['1080p', 'Subbed'],
    featured: false,
    trending: false,
    topRated: false,
    waifuFav: true,
  },
];

// Filtered lists for different rows
export const TRENDING_ANIME = ANIME_CATALOG.filter((a) => a.trending);
export const TOP_RATED_ANIME = ANIME_CATALOG.filter((a) => a.topRated);
export const WAIFU_FAV_ANIME = ANIME_CATALOG.filter((a) => a.waifuFav);
export const FEATURED_ANIME = ANIME_CATALOG.find((a) => a.featured) || ANIME_CATALOG[0];
export const HERO_ANIME_LIST = ANIME_CATALOG.filter((a) => a.featured || a.trending).slice(0, 4);

// Waifu avatar options for profile page
export const WAIFU_AVATARS = [
  { id: 'av1', name: 'Sakura', src: 'https://picsum.photos/seed/av1/120/120', rarity: 'Common' },
  { id: 'av2', name: 'Hana', src: 'https://picsum.photos/seed/av2/120/120', rarity: 'Rare' },
  { id: 'av3', name: 'Rei', src: 'https://picsum.photos/seed/av3/120/120', rarity: 'Epic' },
  { id: 'av4', name: 'Yuki', src: 'https://picsum.photos/seed/av4/120/120', rarity: 'Common' },
  { id: 'av5', name: 'Nami', src: 'https://picsum.photos/seed/av5/120/120', rarity: 'Rare' },
  { id: 'av6', name: 'Shiori', src: 'https://picsum.photos/seed/av6/120/120', rarity: 'Legendary' },
  { id: 'av7', name: 'Akira', src: 'https://picsum.photos/seed/av7/120/120', rarity: 'Epic' },
  { id: 'av8', name: 'Misaki', src: 'https://picsum.photos/seed/av8/120/120', rarity: 'Common' },
];

// Mascot speech bubbles
export const MASCOT_MESSAGES = [
  'Konnichiwa, Senpai! 👋 Ready to binge?',
  'New episodes just dropped! ✨',
  'Your watchlist is calling~ 📺',
  'Sugoi! You have great taste! 🌸',
  'Don\'t forget to bookmark your favs! 🔖',
  'Ara ara~ Another marathon session? 😏',
  'YATTA! You found a hidden gem! 💎',
  'Nani?! That plot twist was wild! 😱',
  'OST of the day: Neon Blade Opening! 🎵',
  'Level up your watchlist, onii-chan! ⭐',
];

// Admin fake stats
export const FAKE_STATS = {
  liveViewers: 14872,
  totalUsers: 284391,
  episodesHosted: 12847,
  dailyStreams: 94201,
};
